I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 92, in script call
    call waterMonFight
  File "game/WaterMonsterfight.rpy", line 3, in script
    while wmHp > 0:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 92, in script call
    call waterMonFight
  File "game/WaterMonsterfight.rpy", line 3, in script
    while wmHp > 0:
  File "/Users/jassherrin/Downloads/renpy-8.3.4-sdk/renpy/execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

macOS-14.6.1-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Drowning in bubbles 1.0
Sun Jan 26 00:57:39 2025
